window.NOTES_CONTENT = {
  index: `\n[FIELD NOTES — TRANSMISSION LOG]\n\nLatest transmissions. Short-form structural diagnostics.\n\n  [6]  when-systems-stop-metabolizing-truth\n       6 min · 2026-02-20\n\n  [7]  the-attention-economy-eats-itself\n       4 min · 2026-02-15\n\n  [8]  identity-is-not-a-position\n       5 min · 2026-02-10\n\n  [9]  fragmentation-as-default\n       3 min · 2026-02-05\n\n  [10] the-noise-floor-rises\n       4 min · 2026-01-28\n\nType 'open <n>' to read.`,
  items: {
    6: `[FIELD NOTE #6]\nWHEN SYSTEMS STOP METABOLIZING TRUTH\n\nA healthy system can absorb correction.\nAn unhealthy system punishes correction and rewards simulation.\n\nYou can track failure by one metric:\nHow expensive is it to say what is?\n\nWhen truth becomes socially expensive, delusion becomes structurally\ncheap. Then collapse is only a timing question.`,
    7: `[FIELD NOTE #7]\nTHE ATTENTION ECONOMY EATS ITSELF\n\nEvery platform eventually optimizes for what spikes.\nSpike content increases arousal, outrage, identity threat.\n\nShort-term result: engagement.\nLong-term result: civilizational attention damage.\n\nA system that monetizes fragmentation cannot produce coherence by\naccident. It must be redesigned intentionally.`,
    8: `[FIELD NOTE #8]\nIDENTITY IS NOT A POSITION\n\nIdentity answers "who am I in relation to others?"\nPosition answers "where am I in relation to reality?"\n\nMost discourse confuses the two.\n\nReality does not negotiate with identities.\nIt responds to structure, density, and consequence.`,
    9: `[FIELD NOTE #9]\nFRAGMENTATION AS DEFAULT\n\nFragmentation is now the baseline operating condition.\nNot because people disagree.\nBecause coordination languages are no longer compatible.\n\nWhen shared ontology disappears, every decision becomes tribal\ntheater. Then institutions can perform continuity while function\nsilently dies.`,
    10: `[FIELD NOTE #10]\nTHE NOISE FLOOR RISES\n\nIf noise rises faster than signal, discernment becomes a luxury.\nPeople outsource judgment to tribe, vibe, and algorithm.\n\nAt scale, this creates a feedback loop:\nless discernment -> more noise -> less discernment.\n\nBreak the loop by building local, high-trust signal channels.`
  }
};