window.START_CONTENT = {
  index: `\n[START HERE — GUIDED PATH]\n\nFive texts. One map.\nRead in order. Each installs one layer of the lens.\n\n  [1] Noise vs Signal\n      Why attention markets reward fragmentation.\n\n  [2] Identity and Performance\n      How social selves drift from structural truth.\n\n  [3] Collapse Dynamics\n      What breaks first, what breaks last, what pretends to hold.\n\n  [4] Alignment\n      The difference between moral pose and structural fit.\n\n  [5] Coherence Under Pressure\n      What remains when comfort, tribe, and certainty fail.\n\nType 'open 1' to begin.`,
  items: {
    1: `[START #1]\nNOISE VS SIGNAL\n\nMost systems today optimize for engagement, not coherence.\nThat means noise gets rewarded because it spreads faster than truth.\n\nSignal is slower. Signal requires structure, context, and cost.\nNoise is cheap. It copies, mutates, and multiplies instantly.\n\nA civilization enters danger when its attention markets can no\nlonger metabolize correction. At that point, simulation outruns\nfeedback, and feedback is what keeps systems alive.\n\nSignal is not the loudest voice.\nSignal is what survives contact with reality.`,
    2: `[START #2]\nIDENTITY AND PERFORMANCE\n\nIdentity is useful until it hardens into a prison.\nWhen identity becomes primary, reality becomes secondary.\n\nPeople start defending symbols instead of structures.\nInstitutions start preserving image instead of function.\nNarrative becomes armor.\n\nPerformance can mimic coherence for a while.\nBut under pressure, performance collapses because it was never\nload-bearing.\n\nA structural life asks one question:\nAm I aligned with what is, or with what I need to appear as?`,
    3: `[START #3]\nCOLLAPSE DYNAMICS\n\nCollapse is not always failure. It is often selection.\nMany possible futures compete. One becomes real.\n\nWhat breaks first: trust loops.\nWhat breaks second: coordination systems.\nWhat breaks last: visible infrastructure.\n\nBy the time roads crack, the ontology cracked long before.\n\nMost people mistake surface stability for deep stability.\nStructural reading reverses this:\n\n  • language before policy\n  • incentives before language\n  • ontology before incentives\n\nCollapse is history choosing a form.`,
    4: `[START #4]\nALIGNMENT\n\nAlignment is not agreement.\nAlignment is structural fit between perception and reality.\n\nA misaligned system can still look successful short term.\nIt can scale, monetize, and dominate while storing fragility.\n\nAlignment requires revision cost:\nwhen map and world conflict, map must die.\n\nThis is rare. Ego resists it. Institutions punish it.\nBut without revision, delay compounds.\n\nDelay is the tax civilization pays for refusing what is.`,
    5: `[START #5]\nCOHERENCE UNDER PRESSURE\n\nAnyone can seem coherent in calm conditions.\nPressure reveals geometry.\n\nWhen certainty drops, people default to tribe, identity, and noise.\nCoherence means holding structure when comfort disappears.\n\nPractical markers:\n\n  • Can you update without collapsing self?\n  • Can you act without total certainty?\n  • Can you preserve signal inside a noisy field?\n\nCoherence is not perfection.\nIt is repeated structural honesty under load.`
  }
};